name: Terraform Validation

on: 
  pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    name: Terraform Validation
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

# HIPAA Validation
    - name: Terraform fmt HIPAA
      run: terraform fmt
      working-directory: ./compliance_scp/hipaa_scp
      continue-on-error: true

    - name: Terraform Init HIPAA
      run: terraform init
      working-directory: ./compliance_scp/hipaa_scp

    - name: Terraform Validate HIPAA
      run: terraform validate -no-color
      working-directory: ./compliance_scp/hipaa_scp

    - name: Terraform Plan HIPAA
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/hipaa_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# PCI Validation
    - name: Terraform fmt PCI
      run: terraform fmt
      working-directory: ./compliance_scp/pci_scp
      continue-on-error: true

    - name: Terraform Init PCI
      run: terraform init
      working-directory: ./compliance_scp/pci_scp

    - name: Terraform Validate PCI
      run: terraform validate -no-color
      working-directory: ./compliance_scp/pci_scp

    - name: Terraform Plan PCI
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/pci_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# SOC Validation
    - name: Terraform fmt SOC
      run: terraform fmt
      working-directory: ./compliance_scp/soc_scp
      continue-on-error: true

    - name: Terraform Init SOC
      run: terraform init
      working-directory: ./compliance_scp/soc_scp

    - name: Terraform Validate SOC
      run: terraform validate -no-color
      working-directory: ./compliance_scp/soc_scp

    - name: Terraform Plan SOC
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/soc_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# ISO Validation
    - name: Terraform fmt ISO
      run: terraform fmt
      working-directory: ./compliance_scp/iso_scp
      continue-on-error: true

    - name: Terraform Init ISO
      run: terraform init
      working-directory: ./compliance_scp/iso_scp

    - name: Terraform Validate ISO
      run: terraform validate -no-color
      working-directory: ./compliance_scp/iso_scp

    - name: Terraform Plan ISO
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/iso_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# FedRAMP Medium Validation
    - name: Terraform fmt FedRAMP Med
      run: terraform fmt
      working-directory: ./compliance_scp/fedrampMed_scp
      continue-on-error: true

    - name: Terraform Init FedRAMP Med
      run: terraform init
      working-directory: ./compliance_scp/fedrampMed_scp

    - name: Terraform Validate FedRAMP Med
      run: terraform validate -no-color
      working-directory: ./compliance_scp/fedrampMed_scp

    - name: Terraform Plan FedRAMP Med
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/fedrampMed_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# FedRAMP High Validation
    - name: Terraform fmt FedRAMP High
      run: terraform fmt
      working-directory: ./compliance_scp/fedrampHigh_scp
      continue-on-error: true

    - name: Terraform Init FedRAMP High
      run: terraform init
      working-directory: ./compliance_scp/fedrampHigh_scp

    - name: Terraform Validate FedRAMP High
      run: terraform validate -no-color
      working-directory: ./compliance_scp/fedrampHigh_scp

    - name: Terraform Plan FedRAMP High
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./compliance_scp/fedrampHigh_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'

# Security Controls Validation
    - name: Terraform fmt Security Controls
      run: terraform fmt
      working-directory: ./security_controls_scp
      continue-on-error: true

    - name: Terraform Init Security Controls
      run: terraform init
      working-directory: ./security_controls_scp

    - name: Terraform Validate Security Controls
      run: terraform validate -no-color
      working-directory: ./security_controls_scp

    - name: Terraform Plan Security Controls
      run: terraform plan -no-color
      continue-on-error: false
      working-directory: ./security_controls_scp
      env:
        TF_VAR_target_id: ${{ secrets.TARGET_ID }}"'
        TF_VAR_ami_creator_account: ${{ secrets.AMI_CREATOR_ACCOUNT }}"'
        TF_VAR_ami_tag_key: ${{ secrets.AMI_TAG_KEY }}"'
        TF_VAR_ami_tag_value: ${{ secrets.AMI_TAG_VALUE }}"'